[package]
name = "rust_example"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.17.0", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
